### PR TITLE
It is a workaround to address the #2027 issue.

### PR DESCRIPTION
**Pull request by kemaruya**
I implemented a workaround for the #2027 issue.

# PR Summary

- Implemented the mresetconsole function.
- added call to atexit function so that mresetconsole function is called before program termination when msetconsole is called

## PR Context

I wrote a workaround to address the #2027 issue.

### CODE REVIEW

**Review by mgkuhn — CHANGES_REQUESTED** [review]
According to the [SetConsoleOutputCP documentation](https://learn.microsoft.com/en-us/windows/console/setconsoleoutputcp), the return value of this function is of type BOOL, and if it “succeeds, the return value is nonzero”. The documentation does _not_ promise that SetConsoleOutputCP will return the previous code page. Instead, it says “To determine a console's current output code page, use the [GetConsoleOutputCP](https://learn.microsoft.com/en-us/windows/console/getconsoleoutputcp) function.” Therefore I would suggest instead
```
g_previous_codepage = GetConsoleOutputCP();
SetConsoleOutputCP(CP_UTF8);
```

**Review by mgkuhn — COMMENTED** [review]
I would have called the new function `mrestorelocale` instead of `mresetlocale`, because the verb “restore” is more commonly used to describe the act of bringing back a system into a previous state.

**Comment by kemaruya** [comment]
Thank you for good comment, I have updated the code.

**Review by mgkuhn — APPROVED** [review]
Thanks, looks good.

**Review by PaulHigin — APPROVED** [review]
LGTM

**Review by vthiebaut10 — APPROVED** [review]

**Pull request merged**
