### PR TITLE
Compile test v8.2 1

### PR DESCRIPTION
**Pull request by holdenhightime2**

### CODE REVIEW

**Comment by ghost** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/PowerShell/openssh-portable?pullRequest=532) <br/>All CLA requirements met.

**Comment by bagajjal** [comment]
@holdenhightime2 - What are you trying to PR? There are changes to 220 files and this PR doesn't even have a description.
We already released V8.6.

**Comment by catthehacker** [comment]
@bagajjal it's spam account, I've seen such actions in many other repositories (most often in actions/virtual-environments)

**Comment by bagajjal** [comment]
> @bagajjal it's spam account, I've seen such actions in many other repositories (most often in actions/virtual-environments)

Thanks for your reply. I will close this PR if I didn't hear back in a day

**Pull request closed without merging**
