### PR TITLE
Escape quotes in scp arguments to ssh

### PR DESCRIPTION
**Pull request by cbookg**
fixes:
PowerShell/Win32-OpenSSH#1211

### CODE REVIEW

**Comment by manojampalam** [comment]
Thanks for the fix. I'll have it keep it on hold for now, while we figure out an accurate way to implement execv() equivalent on Windows.

**Comment by cbookg** [comment]
Is there a concern with the current patch?  I believe what is missing from a complete solution would be support for backslash escaping as well.

**Comment by cbookg** [comment]
Sorry to pester you @manojampalam , but can I help with what you're looking for in terms of the execv implementation?  I'm willing to put in more work on this so as not to have to maintain my own fork/release in my project.

**Comment by manojampalam** [comment]
Sorry for the delay @cbookg. There isn't a specific concern here. We are working on refactoring session process launching in session.c. It is currently using CreateProcess directly, but the goal is to move it towards posix_spawn model. The problem is that shells in Windows behave different wrt parsing commandline parameters. 
cmd.exe with /c argument consumes the rest of the commandline literally, while powershell.exe and other shells rely on argv (that Windows CRT spits using its parsing rules). 

The goal here is to accomodate all these variations in a way that still keeps the core code clean and understandable from a non-Windows contributer point of view, since we eventually want the uber community to welcome and to support our changes in OpenSSH's main repository.

**Comment by bingbing8** [comment]
@cbookg, thanks for your contribution and patient. we added support of escaping in posix_spawn. quotes in scp arguments should be escaped now. Can we close this PR?

**Comment by cbookg** [comment]
great!  closing.

**Pull request closed without merging**
