### PR TITLE
Change /dev/null to NUL

### PR DESCRIPTION
**Pull request by sasdf**
In windows, null device is `NUL` not default `/dev/null`.
And `system` refuse to run command when redirect to `/dev/null` in windows.

With this patch, untrusted X11 forwarding `-X` works with proper environ and latest xauth from VcXsrv (commit 198013, not released yet).

### CODE REVIEW

**Comment by ghost** [comment]
seems nice. but won't this need more changes in the rest of the code?

ignore, if you have tested and  found no issues.
---

and if anyone has any updates, please don't forget to post about when VcXsrv (commit 198013) got released.
with a link.
----
**peace out**
_ghostArch_

**Comment by sasdf** [comment]
I've checked all references to `_PATH_DEVNULL` and added some more fix to `w32_open`.
There are still some hardcoded `/dev/null` in error messages from upstream, but it won't affect functionality.

For anyone who would like to test it, you could find my unofficial prebuilt x64 binary from following links: [ssh](https://ci.appveyor.com/project/sasdf/openssh-portable/build/artifacts) and [vcxsrv](https://ci.appveyor.com/project/sasdf/vcxsrv/build/artifacts).
To make xauth working, you have to set two environment variables: `DISPLAY` and `TMPDIR`. And then specify path to xauth in ssh config like:
```
Host *
    XAuthLocation C:\Progra~1\VcXsrv\xauth.exe
```
(Note that you should avoid spaces in path)

**Comment by bagajjal** [comment]
@sasdf - I am getting an error. FYI, e:\\balu\\temp has full permissions to "Users" on my machine so it can't be the permission issue.

debug2: channel_input_open_confirmation: channel 0: callback start
debug2: client_x11_get_proto: xauth command: C:\\Progra~1\\VcXsrv\\xauth.exe -f E:\\balu\\temp/ssh-WmFPW41IJeQA/xauthfile generate 1 MIT-MAGIC-COOKIE-1 untrusted timeout 1260 2>NUL
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
debug2: fd 3 setting TCP_NODELAY
debug2: client_session2_setup: id 0

**Comment by bagajjal** [comment]
@sasdf - Please sync with the latest changes and resolve the conflicts.

**Comment by sasdf** [comment]
@bagajjal I guess the error is caused by incorrect `DISPLAY` setting. I set it to `127.0.0.1:0.0`.
Here's how it will looks like:
```
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: client_x11_get_proto: xauth command: C:\\Progra~1\\VcXsrv\\xauth.exe -f C:\\Users\\sasdf\\AppData\\Local\\Temp/ssh-Vp332EMM0yqH/xauthfile generate 127.0.0.1:0.0 MIT-MAGIC-COOKIE-1 untrusted timeout 1260 2>NUL
debug2: x11_get_proto: C:\\Progra~1\\VcXsrv\\xauth.exe -f C:\\Users\\sasdf\\AppData\\Local\\Temp/ssh-Vp332EMM0yqH/xauthfile list 127.0.0.1:0.0 2>NUL
debug1: Requesting X11 forwarding with authentication spoofing.
debug2: channel 0: request x11-req confirm 1
debug2: fd 3 setting TCP_NODELAY
```

Let me know if the problem still occurs. Please also provide the error messages by running that xauth command manually with and without stderr redirection.

BTW, I have noticed that SIGINT is not handled correctly with x forwarding enabled (more precisely: after calling `client_x11_get_proto`). The bug already exists on lastest master, so I think I may create another PR for that after debugging.

**Comment by bagajjal** [comment]
@sasdf - I am still getting the error message. I am fine with the changes in this PR. There seems to be a test failure (ProxyCommand with absolute path to the file).
I am trying to understand the scenario of x11 authentication. Please provide details.

```
PS C:\> C:\Progra~1\VcXsrv\xauth.exe -f E:\balu\temp/ssh-Odq8PpgzsTeg/xauthfile generate 127.0.0.1:0.0 MIT-MAGIC-COOKIE-1 untrusted timeout 1260
C:\Progra~1\VcXsrv\xauth.exe:  error in locking authority file E:\balu\temp\ssh-Odq8PpgzsTeg\xauthfile
PS C:\>
```

**Comment by bagajjal** [comment]
@sasdf - Please fix the test failure

**Comment by sasdf** [comment]
@bagajjal the error message is due to the absence of temporary folder `E:\balu\temp/ssh-Odq8PpgzsTeg/`. Could you create it and run the command again?
(It's a temp dir created when running `ssh -X` and will be removed after generating x cookie.)

And the test failure is propagated from current master, I'll pull again after it's fixed.

**Comment by bagajjal** [comment]
@sasdf - Looks like you didn't have the latest changes. I don't see bash test execution.
Anyways, I will merge the PR as it's not related.

**Pull request merged**
