### PR TITLE
Fix a race condition between read and cancel.

### PR DESCRIPTION
**Pull request by nullcatalyst**
Retry CancelSynchronousIo until the read thread exits. This avoids a
concurrency issue, where we call CancelSynchronousIo before the read
thread has called ReadFile. Reading after the cancel causes a hang until
the user presses Enter which is undesirable for scripting.

### CODE REVIEW

**Comment by nullcatalyst** [comment]
I just felt that I should mention that this may not be the best solution, I just wanted to make people aware of a problem -- hopefully explaining it in a way that was easy enough to understand -- that would make it easier for someone else to fix properly.

**Comment by NoMoreFood** [comment]
@nullcatalyst I revised some of this code awhile back to try to mitigate this problem which was effective to *some* degree but not totally as you've discovered.  Curious... what tests have you been using to demonstrate the issue and subsequently validate your changes?

**Comment by bagajjal** [comment]
@nullcatalyst  - Can you please address @NoMoreFood comment about the tests and how you validated your changes.

**Comment by bagajjal** [comment]
@nullcatalyst  - Can you please address @NoMoreFood comment about the tests and how you validated your changes.

**Comment by bagajjal** [comment]
Closing this PR as there is no follow up answer from the PR author.

**Pull request closed without merging**
