### PR TITLE
Send full auth context to authorized sshd child

### LINKED ISSUE #1252: User resolution doesn't work if user name is the same as host name
**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

7.7.2.0
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows 10 Pro

**Client OperatingSystem**

Ubuntu 18.04

**What is failing**
I am getting a broken pipe when trying to authenticate.
**Expected output**
I should auth correctly.
**Actual output**
```
debug1: sshd version OpenSSH_for_Windows_7.7, LibreSSL 2.6.4
debug3: ssh_msg_recv entering
debug3: ssh_msg_recv entering
debug2: fd 4 setting O_NONBLOCK
debug3: ssh_msg_recv entering
debug2: parse_server_config: config reprocess config len 159
debug3: get_passwd: Invalid account type: 3.
Invalid user ethanhs from 10.147.18.212 port 45922
debug3: mm_request_receive entering
debug1: do_cleanup
sshd.exe exited on ETHANHS with error code 255.
```

Client side:

```
debug1: Next authentication method: password
ethanhs\ethanhs@10.147.18.113's password: 
debug3: send packet: type 50
debug2: we sent a password packet, wait for reply
debug3: receive packet: type 52
debug1: Authentication succeeded (password).
Authenticated to 10.147.18.113 ([10.147.18.113]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network
debug3: send packet: type 1
packet_write_wait: Connection to 10.147.18.113 port 22: Broken pipe
```

### PR DESCRIPTION
**Pull request by bagajjal**
Fixes https://github.com/PowerShell/Win32-OpenSSH/issues/1252

When we trying to do ssh using MS account (ex - abcd@outlook.com) that is same as the machine name (abcd) then ssh connection will fail.

### CODE REVIEW

**Comment by bagajjal** [comment]
@oldium - Can you try the attached private sshd executable.
1) net stop sshd
2) backup existing sshd.exe
3) copy my private sshd.exe
4) net start sshd
5) on powershell window, run "gps sshd |fl *". Make sure the version is "8.1.0.0"
6) do ssh on a machine where username, machine name are same.

[sshd_fix_Same_username_machinename_issue.zip](https://github.com/PowerShell/openssh-portable/files/3962665/sshd_fix_Same_username_machinename_issue.zip)

**Comment by oldium** [comment]
@bagajjal Thanks, works perfectly fine. I am able to login with `ssh -l OLDIUM\oldium ...` and also with my MS account.

**Comment by oldium** [comment]
Is the latest commit somehow related to PowerShell/openssh-portable#418? I have tested it and problem persists, because get_passwd is called with NULL user_utf16 argument, but non-NULL sid (see pwd.c line 369) from w32_getpwuid() from ssh client's main(). So the additional check does not apply.

**Comment by bagajjal** [comment]
#418 fixes this issue by converting local user having same name as computer name to "<username aka comptuername>//<username aka comptuername>"

**Pull request closed without merging**
