### PR TITLE
fix: fix bind interface

### PR DESCRIPTION
**Pull request by j3l11234**
Fix the bug of https://github.com/PowerShell/Win32-OpenSSH/issues/1442

### CODE REVIEW

**Review by tgauth — COMMENTED** [review]
Thanks for the contribution, @j3l11234 - I think this would work. 

Might it be better to eliminate one of the duplicate bind calls, in order to ensure that this doesn't unintentionally miss a valid EINVAL error, though? Perhaps by adding `#ifndef Windows` in https://github.com/PowerShell/openssh-portable/blob/latestw_all/sshconnect.c#L449?

**Comment by j3l11234** [comment]
@tgauth  Yes, I have tried to do this, But only the bind() of https://github.com/PowerShell/openssh-portable/blob/latestw_all/sshconnect.c#L449  can make the binding interface works. 
And the https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-bind says that WSAEINVAL only happens when the socket s is already bound to an address.  So I decided to change the "win32compat" which means it is just for compat.
I think maybe is the best solution now.

**Comment by tgauth** [comment]
@bagajjal - wanted to get your thoughts here.

**Comment by j3l11234** [comment]
any update?

**Comment by tgauth** [comment]
we are still investigating the feasibility of eliminating the bind() call in win32compat during -b scenarios - thanks for your patience!

**Comment by adison** [comment]
> we are still investigating the feasibility of eliminating the bind() call in win32compat during -b scenarios - thanks for your patience!

Any luck? I am using bind address on windows and blocked by this issue.
By the way, I tried -D and not work
```ssh -D 192.168.0.111:22 root@192.168.0.1```

**Review by tgauth — APPROVED** [review]
LGTM

**Pull request merged**
